# Generated by Django 6.0.5 on 2026-05-18 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Championship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(unique=True, verbose_name='Ano')),
                ('description', models.CharField(max_length=100, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Título',
                'verbose_name_plural': 'Títulos',
                'ordering': ['year'],
            },
        ),
        migrations.CreateModel(
            name='HistoryEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(verbose_name='Ano')),
                ('title', models.CharField(max_length=100, verbose_name='Título')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('order', models.PositiveIntegerField(unique=True, verbose_name='Ordem na Timeline')),
            ],
            options={
                'verbose_name': 'Evento Histórico',
                'verbose_name_plural': 'Eventos Históricos',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('number', models.PositiveIntegerField(verbose_name='Número da Camisa')),
                ('position', models.CharField(choices=[('PG', 'Point Guard'), ('SG', 'Shooting Guard'), ('SF', 'Small Forward'), ('PF', 'Power Forward'), ('C', 'Center'), ('PF/C', 'Power Forward/Center'), ('SG/SF', 'Shooting Guard/Small Forward')], max_length=5, verbose_name='Posição (sigla)')),
                ('position_full', models.CharField(max_length=50, verbose_name='Posição (completa)')),
                ('height', models.CharField(max_length=10, verbose_name='Altura')),
                ('experience', models.CharField(max_length=20, verbose_name='Experiência')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='players/', verbose_name='Foto (upload)')),
                ('photo_url', models.URLField(blank=True, null=True, verbose_name='Foto (URL externa)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo no Elenco')),
                ('is_legend', models.BooleanField(default=False, verbose_name='Lenda do Clube')),
                ('legend_years', models.CharField(blank=True, help_text='Ex: 1997-2016', max_length=20, null=True, verbose_name='Período (lendas)')),
                ('legend_achievements', models.CharField(blank=True, help_text='Ex: 19 temporadas, 5 títulos, 2 MVPs', max_length=200, null=True, verbose_name='Conquistas (lendas)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
            ],
            options={
                'verbose_name': 'Jogador',
                'verbose_name_plural': 'Jogadores',
                'ordering': ['number'],
            },
        ),
    ]
