# Generated by Django 6.0.2 on 2026-05-20 19:53

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_player_created_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Emprestimo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(choices=[('camisa', 'Camisa Oficial'), ('bone', 'Boné Oficial'), ('camiseta', 'Camiseta Comemorativa'), ('poster', 'Poster Autografado'), ('dvd', 'DVD de Campeonato')], default='camisa', max_length=50, verbose_name='Item Emprestado')),
                ('descricao', models.CharField(max_length=200, verbose_name='Descrição')),
                ('data_emprestimo', models.DateField(default=django.utils.timezone.now, verbose_name='Data do Empréstimo')),
                ('data_devolucao', models.DateField(verbose_name='Data de Devolução')),
                ('devolvido', models.BooleanField(default=False, verbose_name='Devolvido?')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emprestimos', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Empréstimo',
                'verbose_name_plural': 'Empréstimos',
                'ordering': ['data_devolucao'],
                'permissions': [('cadastrar_emprestimo', 'Pode cadastrar empréstimos'), ('listar_emprestimo', 'Pode listar empréstimos')],
            },
        ),
    ]
