# Generated by Django 6.0.2 on 2026-05-20 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_add_emprestimo_model'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Emprestimo',
        ),
    ]
